spring:
  application:
    name: auth-server
  security:
    user:
      # 账号
      name: admin
      # 密码
      password: admin
  datasource:
    url: jdbc:mysql://localhost:3306/security-test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
  redis:
    host: 192.168.99.100
    port: 6379
    password:
server:
  port: 8080